name: Igor Ivanovic
title: About me
description: Hey, I’m Igor. I’m a software engineer living in Munich, Germany. I am a fan of technology, travel, and cycling. I’m also interested in coffee and programming.
url: http://www.igorivanovic.info
repository: https://github.com/igorzg

theme: jekyll-theme-architect

exclude:
  - .gitignore

twitter:
  username: igorzg1987
