name: Igor Ivanovic
title: Igor Ivanovic blog page
description: Writing about technology, programming, team management, coding
url: http://www.igorivanovic.info

theme: jekyll-theme-hacker

exclude:
  - .gitignore

twitter:
  username: igorzg1987
